- hosts: server2

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: true
      become_user: root
      become_method: sudo
      retries: 10
      delay: 5
